// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfhw3iDFe0n-54hE_yoexpbx9HTGwqpak',
    appId: '1:362284469535:web:0830f72d8c96544b30b42a',
    messagingSenderId: '362284469535',
    projectId: 'project-recette-new',
    authDomain: 'project-recette-new.firebaseapp.com',
    storageBucket: 'project-recette-new.firebasestorage.app',
    measurementId: 'G-3P8RQVQ6N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM1on8EapWXOQ2XYpy7Ky5QbMccm8JnmI',
    appId: '1:362284469535:android:c5a545a0b8ffee9f30b42a',
    messagingSenderId: '362284469535',
    projectId: 'project-recette-new',
    storageBucket: 'project-recette-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsjCclr7_yiyVqLFql4zOJtZhgqdRbV7A',
    appId: '1:362284469535:ios:48d18fadfb15848130b42a',
    messagingSenderId: '362284469535',
    projectId: 'project-recette-new',
    storageBucket: 'project-recette-new.firebasestorage.app',
    iosBundleId: 'com.example.projetrecette',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsjCclr7_yiyVqLFql4zOJtZhgqdRbV7A',
    appId: '1:362284469535:ios:48d18fadfb15848130b42a',
    messagingSenderId: '362284469535',
    projectId: 'project-recette-new',
    storageBucket: 'project-recette-new.firebasestorage.app',
    iosBundleId: 'com.example.projetrecette',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfhw3iDFe0n-54hE_yoexpbx9HTGwqpak',
    appId: '1:362284469535:web:e3ea91e22db1101830b42a',
    messagingSenderId: '362284469535',
    projectId: 'project-recette-new',
    authDomain: 'project-recette-new.firebaseapp.com',
    storageBucket: 'project-recette-new.firebasestorage.app',
    measurementId: 'G-CB8XD0X96S',
  );
}
