// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvEVbZaQXN9JyvT6mg_eBiUQLE8FkreyU',
    appId: '1:812750370405:web:2cf471bc789784eb7db88c',
    messagingSenderId: '812750370405',
    projectId: 'flutter-recette-oct-2025',
    authDomain: 'flutter-recette-oct-2025.firebaseapp.com',
    storageBucket: 'flutter-recette-oct-2025.firebasestorage.app',
    measurementId: 'G-D5VSZVX7ZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuTUUTopNx8-h6jWNMYxfXM9sRgv4Eu78',
    appId: '1:812750370405:android:dbce4e52c69e7d2f7db88c',
    messagingSenderId: '812750370405',
    projectId: 'flutter-recette-oct-2025',
    storageBucket: 'flutter-recette-oct-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIxsVbuP1qewY6ceCBLhvS3q0ADlG0D7s',
    appId: '1:812750370405:ios:d164d5c137d71ce27db88c',
    messagingSenderId: '812750370405',
    projectId: 'flutter-recette-oct-2025',
    storageBucket: 'flutter-recette-oct-2025.firebasestorage.app',
    iosBundleId: 'com.example.projetrecette',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIxsVbuP1qewY6ceCBLhvS3q0ADlG0D7s',
    appId: '1:812750370405:ios:d164d5c137d71ce27db88c',
    messagingSenderId: '812750370405',
    projectId: 'flutter-recette-oct-2025',
    storageBucket: 'flutter-recette-oct-2025.firebasestorage.app',
    iosBundleId: 'com.example.projetrecette',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvEVbZaQXN9JyvT6mg_eBiUQLE8FkreyU',
    appId: '1:812750370405:web:6e589751bae9c35c7db88c',
    messagingSenderId: '812750370405',
    projectId: 'flutter-recette-oct-2025',
    authDomain: 'flutter-recette-oct-2025.firebaseapp.com',
    storageBucket: 'flutter-recette-oct-2025.firebasestorage.app',
    measurementId: 'G-SQ3DLL235V',
  );

}